default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: fungiorbis
  password: fungiorbis
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: fungiorbis_development

test: &test
  <<: *default
  database: fungiorbis_test

production:
#  <<: *default
  adapter: mysql2
  encoding: utf8
  url: <%= ENV['APP_DB'] %>

cucumber:
  <<: *test