require 'fungiorbis/old_data_import'

Fungiorbis::OldDataImport.import_users
Fungiorbis::OldDataImport.import_references
Fungiorbis::OldDataImport.import_locations
Fungiorbis::OldDataImport.import_species
Fungiorbis::OldDataImport.import_specimens
Fungiorbis::OldDataImport.import_characteristics